In [2]:
import pandas as pd
non = pd.read_csv('Final_book_details_271.csv')
non2 = pd.read_csv('Final_book_details_272.csv')
non3 = pd.read_csv('Final_book_details_273.csv')
non4 = pd.read_csv('Final_book_details_274.csv')
non5 = pd.read_csv('Final_book_details_275.csv')
non5

/tmp/ipykernel_222840/1065816456.py:5: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  non4 = pd.read_csv('Final_book_details_274.csv')

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best
0,55364,부와 행운을 끌어당기는 우주의 법칙,"“ 무일푼, 무스펙에서 경제적 자유를 이룬젊은 부자 김도사 권마담 부부의성공과 부,...",자기계발,굿웰스북스,김태광(김도사),840.0,"18,000원",95076848.0,0,N
1,55365,우리는 책 읽는 가족입니다,"“독서, 이제는 온가족이 함께 하라!”행복한 가족을 만들고 싶다면 함께 독서하라!“...",자기계발,미다스북스(리틀미다스),정미숙,24.0,"15,000원",95076904.0,0,N
2,55366,1년에 200권 읽으면 일어나는 일,책을 읽는 방법을 바꾸자삶의 많은 것들이 바뀌기 시작했다!“책을 읽으면 대체 뭐가 ...,자기계발,미다스북스(리틀미다스),남영화,36.0,"15,000원",95077005.0,0,N
3,55367,우리 직업은 미래형이라서요,"모두가 프리랜서가 된다는 시대,여성 프리랜서로 무사히 살아남을 수 있을까모두가 프리...",에세이,이음,박초롱,24.0,"15,000원",95077067.0,0,N
4,55368,내가 처음 뇌를 열었을 때,선데이 타임스 베스트셀러신경외과 전문의이자 신경과학자가 들려주는 매력적인 뇌 이야기...,자연과학,윌북(willbook),라훌 잔디얼,372.0,"15,800원",95077356.0,0,N
...,...,...,...,...,...,...,...,...,...,...,...
17784,76788,회복탄력성,“우리가 살면서 겪는 일들은 더 나은 곳으로 향하는 계단이다.”시련과 역경에 굴하지...,자기계발,다른상상,김시현,840.0,"16,800원",128920663.0,0,N
17785,76789,"한 달이라도 좋아, 보홀이라면!","“보홀 한 달 살기, 이제 시작합니다!”엄마와 아들이 손잡고 떠난한 달짜리 여행,눈...",에세이,미다스북스(리틀미다스),박효천,2787.0,"19,000원",128920777.0,0,N
17786,76790,호감의 시작,"*** 커뮤니케이션 분야 1위, 6천만 매력 어드바이저 희렌최 화제작 ****** ...",자기계발,북로망스,희렌최,4242.0,"18,500원",128928568.0,0,N
17787,76791,봄이 오고 그대가 가다,산천초목도 그대 갈 길이 바쁜 걸 알아 일찍이 봄의 것을 내주었던가 보다. 벌써 뒷...,에세이,미루나무,이명길,90.0,"15,000원",128928919.0,0,N
17788,76792,"스물일곱, 과일로 쏘아 올린 200억",도박 빚을 갚기 급급했던 고졸 청년이연매출 200억의 사업가가 되기까지27살 청년 ...,자기계발,차선책,이진우,402.0,"18,400원",128930900.0,0,N

In [3]:
df_non_ = pd.concat([non, non2, non3, non4, non5])
df_non_

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best
0,0,총 균 쇠,문명의 생성과 번영의 수수께끼를 밝힌 세계적 명저마침내 만나는 출간 25년 기념 뉴...,인문,김영사,재레드 다이아몬드,170568.0,"29,800원",118755085.0,0,N
1,1,숙론,“누가 옳은가가 아니라 무엇이 옳은가를 찾으려는 것이다”통섭의 과학자 최재천 교수가...,인문,김영사,최재천,44487.0,"18,000원",126395984.0,0,N
2,2,친애하는 슐츠 씨,“얼마나 많은 차별이 무지에서 비롯되는가?[피너츠]의 첫 흑인 캐릭터부터 여자 옷의...,인문,어크로스,박상현,16779.0,"19,800원",126791092.0,0,N
3,3,가난한 아이들은 어떻게 어른이 되는가,“처음 만날 때는 열예닐곱 살의 청소년이었던 이들이지금은 서른 즈음의 청년이 되었다...,사회 정치,돌베개,강지나,37275.0,"17,500원",123317793.0,8,Y
4,4,팩트풀니스,빌 게이츠가 미국 모든 대학 졸업생에게 직접 선물한 화제의 책강력한 사실을 바탕으로...,인문,김영사,한스 로슬링,43548.0,"19,800원",69724044.0,0,N
...,...,...,...,...,...,...,...,...,...,...,...
17784,76788,회복탄력성,“우리가 살면서 겪는 일들은 더 나은 곳으로 향하는 계단이다.”시련과 역경에 굴하지...,자기계발,다른상상,김시현,840.0,"16,800원",128920663.0,0,N
17785,76789,"한 달이라도 좋아, 보홀이라면!","“보홀 한 달 살기, 이제 시작합니다!”엄마와 아들이 손잡고 떠난한 달짜리 여행,눈...",에세이,미다스북스(리틀미다스),박효천,2787.0,"19,000원",128920777.0,0,N
17786,76790,호감의 시작,"*** 커뮤니케이션 분야 1위, 6천만 매력 어드바이저 희렌최 화제작 ****** ...",자기계발,북로망스,희렌최,4242.0,"18,500원",128928568.0,0,N
17787,76791,봄이 오고 그대가 가다,산천초목도 그대 갈 길이 바쁜 걸 알아 일찍이 봄의 것을 내주었던가 보다. 벌써 뒷...,에세이,미루나무,이명길,90.0,"15,000원",128928919.0,0,N
17788,76792,"스물일곱, 과일로 쏘아 올린 200억",도박 빚을 갚기 급급했던 고졸 청년이연매출 200억의 사업가가 되기까지27살 청년 ...,자기계발,차선책,이진우,402.0,"18,400원",128930900.0,0,N

In [4]:
df_non_.isnull().sum()

index         0
도서 이름         0
줄거리           0
장르            0
출판사          70
작가          111
판매지수     213934
판매가           0
ID            0
month         0
best          0
dtype: int64

In [5]:
df_non_2 = df_non_

In [6]:
# '도서 이름' 열에 결측치가 있는 행을 삭제
df_non_ = df_non_.dropna(subset=['작가'])

# 결과 확인
df_non_

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best
0,0,총 균 쇠,문명의 생성과 번영의 수수께끼를 밝힌 세계적 명저마침내 만나는 출간 25년 기념 뉴...,인문,김영사,재레드 다이아몬드,170568.0,"29,800원",118755085.0,0,N
1,1,숙론,“누가 옳은가가 아니라 무엇이 옳은가를 찾으려는 것이다”통섭의 과학자 최재천 교수가...,인문,김영사,최재천,44487.0,"18,000원",126395984.0,0,N
2,2,친애하는 슐츠 씨,“얼마나 많은 차별이 무지에서 비롯되는가?[피너츠]의 첫 흑인 캐릭터부터 여자 옷의...,인문,어크로스,박상현,16779.0,"19,800원",126791092.0,0,N
3,3,가난한 아이들은 어떻게 어른이 되는가,“처음 만날 때는 열예닐곱 살의 청소년이었던 이들이지금은 서른 즈음의 청년이 되었다...,사회 정치,돌베개,강지나,37275.0,"17,500원",123317793.0,8,Y
4,4,팩트풀니스,빌 게이츠가 미국 모든 대학 졸업생에게 직접 선물한 화제의 책강력한 사실을 바탕으로...,인문,김영사,한스 로슬링,43548.0,"19,800원",69724044.0,0,N
...,...,...,...,...,...,...,...,...,...,...,...
17784,76788,회복탄력성,“우리가 살면서 겪는 일들은 더 나은 곳으로 향하는 계단이다.”시련과 역경에 굴하지...,자기계발,다른상상,김시현,840.0,"16,800원",128920663.0,0,N
17785,76789,"한 달이라도 좋아, 보홀이라면!","“보홀 한 달 살기, 이제 시작합니다!”엄마와 아들이 손잡고 떠난한 달짜리 여행,눈...",에세이,미다스북스(리틀미다스),박효천,2787.0,"19,000원",128920777.0,0,N
17786,76790,호감의 시작,"*** 커뮤니케이션 분야 1위, 6천만 매력 어드바이저 희렌최 화제작 ****** ...",자기계발,북로망스,희렌최,4242.0,"18,500원",128928568.0,0,N
17787,76791,봄이 오고 그대가 가다,산천초목도 그대 갈 길이 바쁜 걸 알아 일찍이 봄의 것을 내주었던가 보다. 벌써 뒷...,에세이,미루나무,이명길,90.0,"15,000원",128928919.0,0,N
17788,76792,"스물일곱, 과일로 쏘아 올린 200억",도박 빚을 갚기 급급했던 고졸 청년이연매출 200억의 사업가가 되기까지27살 청년 ...,자기계발,차선책,이진우,402.0,"18,400원",128930900.0,0,N

In [7]:
import pandas as pd
date = pd.read_csv('date_final_df.csv')
date

                  출간일         ID
0       2023년 05월 10일  118755085
1       2024년 05월 10일  126395984
2       2024년 06월 03일  126791092
3       2023년 11월 06일  123317793
4       2019년 03월 08일   69724044
...               ...        ...
297673  2027년 07월 24일  128920663
297674  2024년 07월 24일  128920777
297675  2024년 07월 23일  128928568
297676  2024년 07월 10일  128928919
297677  2024년 07월 15일  128930900

[297678 rows x 2 columns]

In [8]:
# '출간일'을 날짜 형식으로 변환
date['출간일'] = pd.to_datetime(date['출간일'], format='%Y년 %m월 %d일')

In [9]:
date['year'] = date['출간일'].dt.year
date['month'] = date['출간일'].dt.month
date

              출간일         ID    year  month
0      2023-05-10  118755085  2023.0    5.0
1      2024-05-10  126395984  2024.0    5.0
2      2024-06-03  126791092  2024.0    6.0
3      2023-11-06  123317793  2023.0   11.0
4      2019-03-08   69724044  2019.0    3.0
...           ...        ...     ...    ...
297673 2027-07-24  128920663  2027.0    7.0
297674 2024-07-24  128920777  2024.0    7.0
297675 2024-07-23  128928568  2024.0    7.0
297676 2024-07-10  128928919  2024.0    7.0
297677 2024-07-15  128930900  2024.0    7.0

[297678 rows x 4 columns]

In [10]:
date['year'].unique()

array([2023., 2024., 2019., 2016., 2012., 2021., 2022., 2017., 2018.,
       2004., 2014., 2020., 2010., 2015., 2008., 2013., 2009., 2007.,
       2011., 2002., 2006., 2003., 2001., 2005., 2000., 1999., 1997.,
         nan, 1989., 1996., 1994., 1998., 1995., 1978., 1993., 1985.,
       1991., 1987., 1992., 1981., 1988., 1990., 1986., 1980., 1982.,
       1975., 1983., 1979., 1984., 1976., 1961., 1977., 1970., 1974.,
       1973., 1969., 2027.])

In [11]:
df_non_['year'] = date['year']
df_non_

/tmp/ipykernel_222840/3703781358.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_non_['year'] = date['year']

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
0,0,총 균 쇠,문명의 생성과 번영의 수수께끼를 밝힌 세계적 명저마침내 만나는 출간 25년 기념 뉴...,인문,김영사,재레드 다이아몬드,170568.0,"29,800원",118755085.0,0,N,2023.0
1,1,숙론,“누가 옳은가가 아니라 무엇이 옳은가를 찾으려는 것이다”통섭의 과학자 최재천 교수가...,인문,김영사,최재천,44487.0,"18,000원",126395984.0,0,N,2024.0
2,2,친애하는 슐츠 씨,“얼마나 많은 차별이 무지에서 비롯되는가?[피너츠]의 첫 흑인 캐릭터부터 여자 옷의...,인문,어크로스,박상현,16779.0,"19,800원",126791092.0,0,N,2024.0
3,3,가난한 아이들은 어떻게 어른이 되는가,“처음 만날 때는 열예닐곱 살의 청소년이었던 이들이지금은 서른 즈음의 청년이 되었다...,사회 정치,돌베개,강지나,37275.0,"17,500원",123317793.0,8,Y,2023.0
4,4,팩트풀니스,빌 게이츠가 미국 모든 대학 졸업생에게 직접 선물한 화제의 책강력한 사실을 바탕으로...,인문,김영사,한스 로슬링,43548.0,"19,800원",69724044.0,0,N,2019.0
...,...,...,...,...,...,...,...,...,...,...,...,...
17784,76788,회복탄력성,“우리가 살면서 겪는 일들은 더 나은 곳으로 향하는 계단이다.”시련과 역경에 굴하지...,자기계발,다른상상,김시현,840.0,"16,800원",128920663.0,0,N,2001.0
17785,76789,"한 달이라도 좋아, 보홀이라면!","“보홀 한 달 살기, 이제 시작합니다!”엄마와 아들이 손잡고 떠난한 달짜리 여행,눈...",에세이,미다스북스(리틀미다스),박효천,2787.0,"19,000원",128920777.0,0,N,1995.0
17786,76790,호감의 시작,"*** 커뮤니케이션 분야 1위, 6천만 매력 어드바이저 희렌최 화제작 ****** ...",자기계발,북로망스,희렌최,4242.0,"18,500원",128928568.0,0,N,2001.0
17787,76791,봄이 오고 그대가 가다,산천초목도 그대 갈 길이 바쁜 걸 알아 일찍이 봄의 것을 내주었던가 보다. 벌써 뒷...,에세이,미루나무,이명길,90.0,"15,000원",128928919.0,0,N,2001.0
17788,76792,"스물일곱, 과일로 쏘아 올린 200억",도박 빚을 갚기 급급했던 고졸 청년이연매출 200억의 사업가가 되기까지27살 청년 ...,자기계발,차선책,이진우,402.0,"18,400원",128930900.0,0,N,2001.0

In [12]:
df_non_.isnull().sum()

index         0
도서 이름         0
줄거리           0
장르            0
출판사          70
작가            0
판매지수     213838
판매가           0
ID            0
month         0
best          0
year        126
dtype: int64

In [13]:
df_non_sorted = df_non_.sort_values(by='year', ascending=False)
df_non_sorted

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
65517,18258,세상에서 제일 이상한 그 아이,독특한 스토리 전개로 일본에서 발간 당시 라이트노벨 독자들 사이에서 화제가 됐던 작...,만화/라이트노벨,대원씨아이(단행)(대원키즈),모리야마 유우키,NaN,"6,000원",2953072.0,0,N,2024.0
20093,36449,클리어 The CLEAR 1,마법대륙 사이드리아에 마법사의 천적이 등장했다!대항마법사 사드!!!사드의 대항마법 ...,소설/시/희곡,동아,서영민,NaN,"8,000원",3221359.0,0,N,2024.0
45319,55558,노동조합 100문 100답,『노동조합 100문 100답』개정2판은 2020년 12월 개정된 노조법을 반영202...,사회 정치,매일노동뉴스,박성우,732.0,"20,000원",96432068.0,0,N,2024.0
20123,36480,미인계,중국 춘추시대 월나라의 서시를 비롯하여 당나라 양귀비까지 중국역사상 가장 아름답다고...,소설/시/희곡,오디북스,왕공상,NaN,"12,000원",3219656.0,0,N,2024.0
45320,55559,생활 속 법률 상식사전,"근처 변호사 사무실이 어디에 있었나하는 생각이 간절해지는 순간,하얘지는 머리, 새까...",사회 정치,길벗,김계형,486.0,"14,000원",77709451.0,0,N,2024.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2671,58626,기시미 이치로의 삶과 죽음,"인생은 진화가 아니라 변화다! 젊음과 늙음, 건강과 질병에 우열은 없다!기시미 이치...",인문,에쎄이,기시미 이치로,156.0,"15,000원",101903844.0,0,N,NaN
6538,63147,"아무튼, 피아노","“모든 것은 건반으로부터 시작된다”『아무튼, 피아노』나는 피아노를 배움으로써돌이킬 ...",에세이,제철소,김겨울,1020.0,"12,000원",108454817.0,2,Y,NaN
6724,63375,난세를 살아가는 지략 2,"손자병법, 명심보감 등과 같은 고전의 내용을 엮어 치열한 세상을 살아가는데 필요한 ...",자기계발,조은,범대진,12.0,"20,000원",108789289.0,0,N,NaN
10520,68144,생각의 끈 (큰글자도서),[생각의 끈]은 많은 생각보다는 좋은 생각을 하며 그것을 바르게 이루며 살 것을 말...,자기계발,이담북스(이담Books),양창삼,NaN,"35,000원",117313592.0,0,N,NaN
15940,74600,성과관리 답을 찾다,일 잘하는 S등급 동료의 성과창출 핵심 비결!‘나는 왜 성과를 창출하지 못할까?’가...,자기계발,트로이목마,류랑도,792.0,"22,000원",125104561.0,0,N,NaN

In [14]:
df_non_sorted = df_non_sorted.dropna(subset=['year'])
df_non_sorted

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
65517,18258,세상에서 제일 이상한 그 아이,독특한 스토리 전개로 일본에서 발간 당시 라이트노벨 독자들 사이에서 화제가 됐던 작...,만화/라이트노벨,대원씨아이(단행)(대원키즈),모리야마 유우키,NaN,"6,000원",2953072.0,0,N,2024.0
20093,36449,클리어 The CLEAR 1,마법대륙 사이드리아에 마법사의 천적이 등장했다!대항마법사 사드!!!사드의 대항마법 ...,소설/시/희곡,동아,서영민,NaN,"8,000원",3221359.0,0,N,2024.0
45319,55558,노동조합 100문 100답,『노동조합 100문 100답』개정2판은 2020년 12월 개정된 노조법을 반영202...,사회 정치,매일노동뉴스,박성우,732.0,"20,000원",96432068.0,0,N,2024.0
20123,36480,미인계,중국 춘추시대 월나라의 서시를 비롯하여 당나라 양귀비까지 중국역사상 가장 아름답다고...,소설/시/희곡,오디북스,왕공상,NaN,"12,000원",3219656.0,0,N,2024.0
45320,55559,생활 속 법률 상식사전,"근처 변호사 사무실이 어디에 있었나하는 생각이 간절해지는 순간,하얘지는 머리, 새까...",사회 정치,길벗,김계형,486.0,"14,000원",77709451.0,0,N,2024.0
...,...,...,...,...,...,...,...,...,...,...,...,...
36984,18564,사랑받지 못한 어글리,갖은 고난과 역경을 이겨내고영국 최초의 흑인 여성판사가 된 한 소녀의 이야기영국 최...,에세이,오픈하우스,콘스턴스 브리스코,NaN,"12,800원",3662127.0,0,N,1978.0
26155,42808,파란 3,파란만장한 인생이란 이런 것이다!무공서적만 연구하던 불우한 꼽추 청년 장대길.이세계...,소설/시/희곡,동아,서영민,NaN,"8,000원",1951827.0,0,N,1975.0
26155,62387,아인슈타인의 달팽이,"시인이 사는 곳은 “비밀 집회로 가득한 도시”(「( )」), “목마른 인적으로 유리...",소설/시/희곡,문학동네,전기철,NaN,"7,000원",2138017.0,0,N,1975.0
26155,7133,유망 아르바이트 백과사전,아르바이트에 대해서 가능한 많은 정보를 제공하여 아르바이트를 찾고자 하는 대학생들의...,자기계발,눈과마음,"장미영, 장창영, 이수라 공저",NaN,"8,000원",1423584.0,0,N,1975.0
26155,29804,도시의 정치경제학,도시를 둘러싸고 있는 자본의 운동이 지닌 여러 양태에 대해 논의하고 도시생활 속에서...,사회 정치,한울,데이비드 하비 저 / 초의수 역,NaN,"12,000원",250272.0,0,N,1975.0

In [15]:
df_non_sorted['장르'].unique()

array(['만화/라이트노벨', '소설/시/희곡', '사회 정치', '에세이', '인문', '자기계발', '경제 경영',
       '청소년', 'IT 모바일', '대학교재', '잡지', '건강 취미', '예술', '여행', '국어 외국어 사전',
       '어린이', '역사', '자연과학', '종교', '가정 살림', '수험서 자격증', '유아', '인물', '일본도서',
       '오디오북', '소설', '디자인문구', '중고 국내도서', '경영/인문', 'BOOKK(부크크)', '중고등참고서',
       '초등참고서'], dtype=object)

In [16]:
# 추출할 장르 목록
genres_to_extract = ['사회 정치', '소설/시/희곡', '에세이', '자기계발']

# 장르 열이 지정된 값 중 하나인 행만 추출
df_non_sorted = df_non_sorted[df_non_sorted['장르'].isin(genres_to_extract)]

# 결과 출력
print("Filtered Book Details:")
df_non_sorted

Filtered Book Details:

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
20093,36449,클리어 The CLEAR 1,마법대륙 사이드리아에 마법사의 천적이 등장했다!대항마법사 사드!!!사드의 대항마법 ...,소설/시/희곡,동아,서영민,NaN,"8,000원",3221359.0,0,N,2024.0
45319,55558,노동조합 100문 100답,『노동조합 100문 100답』개정2판은 2020년 12월 개정된 노조법을 반영202...,사회 정치,매일노동뉴스,박성우,732.0,"20,000원",96432068.0,0,N,2024.0
20123,36480,미인계,중국 춘추시대 월나라의 서시를 비롯하여 당나라 양귀비까지 중국역사상 가장 아름답다고...,소설/시/희곡,오디북스,왕공상,NaN,"12,000원",3219656.0,0,N,2024.0
45320,55559,생활 속 법률 상식사전,"근처 변호사 사무실이 어디에 있었나하는 생각이 간절해지는 순간,하얘지는 머리, 새까...",사회 정치,길벗,김계형,486.0,"14,000원",77709451.0,0,N,2024.0
45325,55565,상속재산 분할심판청구,"이번 개정판에서는 상속재산분할, 유류분반환청구 등에 관하여 2020년 3월 이후 선...",사회 정치,지혜와지식,오경수,288.0,"18,000원",121567014.0,0,N,2024.0
...,...,...,...,...,...,...,...,...,...,...,...,...
36984,18564,사랑받지 못한 어글리,갖은 고난과 역경을 이겨내고영국 최초의 흑인 여성판사가 된 한 소녀의 이야기영국 최...,에세이,오픈하우스,콘스턴스 브리스코,NaN,"12,800원",3662127.0,0,N,1978.0
26155,42808,파란 3,파란만장한 인생이란 이런 것이다!무공서적만 연구하던 불우한 꼽추 청년 장대길.이세계...,소설/시/희곡,동아,서영민,NaN,"8,000원",1951827.0,0,N,1975.0
26155,62387,아인슈타인의 달팽이,"시인이 사는 곳은 “비밀 집회로 가득한 도시”(「( )」), “목마른 인적으로 유리...",소설/시/희곡,문학동네,전기철,NaN,"7,000원",2138017.0,0,N,1975.0
26155,7133,유망 아르바이트 백과사전,아르바이트에 대해서 가능한 많은 정보를 제공하여 아르바이트를 찾고자 하는 대학생들의...,자기계발,눈과마음,"장미영, 장창영, 이수라 공저",NaN,"8,000원",1423584.0,0,N,1975.0
26155,29804,도시의 정치경제학,도시를 둘러싸고 있는 자본의 운동이 지닌 여러 양태에 대해 논의하고 도시생활 속에서...,사회 정치,한울,데이비드 하비 저 / 초의수 역,NaN,"12,000원",250272.0,0,N,1975.0

In [17]:
df_non_sorted['장르'].unique()

array(['소설/시/희곡', '사회 정치', '에세이', '자기계발'], dtype=object)

In [18]:
year_counts = df_non_sorted.groupby('year').size()
year_counts

year
1975.0        4
1978.0       13
1979.0        4
1980.0        8
1981.0        4
1982.0        6
1983.0        4
1985.0       30
1986.0       18
1987.0       35
1988.0       12
1989.0       53
1990.0      100
1991.0      120
1992.0      146
1993.0      235
1994.0      310
1995.0      492
1996.0      457
1997.0      906
1998.0     1256
1999.0     2218
2000.0     3400
2001.0     3055
2002.0     3779
2003.0     4125
2004.0     6778
2005.0     6731
2006.0     8610
2007.0     9935
2008.0    10772
2009.0    12363
2010.0    12168
2011.0    12860
2012.0    14038
2013.0    11685
2014.0    11689
2015.0    11160
2016.0    10682
2017.0    12024
2018.0    16253
2019.0    15370
2020.0    15967
2021.0    15425
2022.0    14876
2023.0    15450
2024.0     7689
dtype: int64

except_2024

In [19]:
df_non_sorted = df_non_sorted[df_non_sorted['year'] != 2024]
df_non_sorted

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
11853,61041,나는 야한 여자가 좋다,"도덕보다는 본능을, 이성보다는 감성을쉽고 재미있게 읽히는 경쾌한 에세이, 21년만의...",에세이,북리뷰,마광수,294.0,"13,000원",3745571.0,0,N,2023.0
51555,63780,뱀파이어의 별 2,"'뱀파이어의 꽃' 그 마지막 입맞춤,영원불멸의 뱀파이어 로맨스!‘말해서는 안 돼. ...",소설/시/희곡,테라스북,신지은,138.0,"14,500원",29373471.0,0,N,2023.0
51292,33906,수거물 폐기물,■ 사랑의 기억을 모으고 나누고 버리고… 마음이 심플해지는 감정정리법!-카피라이터 ...,에세이,폭스코너,신주희,12.0,"13,800원",20181557.0,0,N,2023.0
53713,36582,군인의 품격,"군인엄마의, 희망군대 만들기 프로젝트아들에게도 엄마에게도, 637일간의 인생수업대한...",에세이,더블엔,최혜경,12,"13,000원",30146604.0,0,N,2023.0
54414,66804,무녀굴,<한국 공포 문학 단편선>에 꾸준히 단편을 발표해 오며 실력을 닦아 온 신진오 작가...,소설/시/희곡,황금가지,신진오,126.0,"13,800원",4096725.0,0,N,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
36984,18564,사랑받지 못한 어글리,갖은 고난과 역경을 이겨내고영국 최초의 흑인 여성판사가 된 한 소녀의 이야기영국 최...,에세이,오픈하우스,콘스턴스 브리스코,NaN,"12,800원",3662127.0,0,N,1978.0
26155,42808,파란 3,파란만장한 인생이란 이런 것이다!무공서적만 연구하던 불우한 꼽추 청년 장대길.이세계...,소설/시/희곡,동아,서영민,NaN,"8,000원",1951827.0,0,N,1975.0
26155,62387,아인슈타인의 달팽이,"시인이 사는 곳은 “비밀 집회로 가득한 도시”(「( )」), “목마른 인적으로 유리...",소설/시/희곡,문학동네,전기철,NaN,"7,000원",2138017.0,0,N,1975.0
26155,7133,유망 아르바이트 백과사전,아르바이트에 대해서 가능한 많은 정보를 제공하여 아르바이트를 찾고자 하는 대학생들의...,자기계발,눈과마음,"장미영, 장창영, 이수라 공저",NaN,"8,000원",1423584.0,0,N,1975.0
26155,29804,도시의 정치경제학,도시를 둘러싸고 있는 자본의 운동이 지닌 여러 양태에 대해 논의하고 도시생활 속에서...,사회 정치,한울,데이비드 하비 저 / 초의수 역,NaN,"12,000원",250272.0,0,N,1975.0

In [20]:
df_non_sorted = df_non_sorted[df_non_sorted['year'] >= 2017]
df_non_sorted

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
11853,61041,나는 야한 여자가 좋다,"도덕보다는 본능을, 이성보다는 감성을쉽고 재미있게 읽히는 경쾌한 에세이, 21년만의...",에세이,북리뷰,마광수,294.0,"13,000원",3745571.0,0,N,2023.0
51555,63780,뱀파이어의 별 2,"'뱀파이어의 꽃' 그 마지막 입맞춤,영원불멸의 뱀파이어 로맨스!‘말해서는 안 돼. ...",소설/시/희곡,테라스북,신지은,138.0,"14,500원",29373471.0,0,N,2023.0
51292,33906,수거물 폐기물,■ 사랑의 기억을 모으고 나누고 버리고… 마음이 심플해지는 감정정리법!-카피라이터 ...,에세이,폭스코너,신주희,12.0,"13,800원",20181557.0,0,N,2023.0
53713,36582,군인의 품격,"군인엄마의, 희망군대 만들기 프로젝트아들에게도 엄마에게도, 637일간의 인생수업대한...",에세이,더블엔,최혜경,12,"13,000원",30146604.0,0,N,2023.0
54414,66804,무녀굴,<한국 공포 문학 단편선>에 꾸준히 단편을 발표해 오며 실력을 닦아 온 신진오 작가...,소설/시/희곡,황금가지,신진오,126.0,"13,800원",4096725.0,0,N,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8570,65655,자기계발 코칭전문가 4,"우리는 지금 어떤 시대에 살고 있는가? 포노 사피엔스 시대!(스마트폰 시대)20,0...",자기계발,BOOKK(부크크),최보규,NaN,"15,100원",112905001.0,0,N,2017.0
29816,68589,모두가 예술이다,계간 문예지 『시와세계』와 『현대불교신문』이 공동으로 제정한 <이상시문학상>은 시인...,소설/시/희곡,시와세계,이승훈,NaN,"8,000원",3081397.0,0,N,2017.0
8573,65658,자기계발 코칭전문가 1,"우리는 지금 어떤 시대에 살고 있는가? 포노 사피엔스 시대!(스마트폰 시대)20,0...",자기계발,BOOKK(부크크),최보규,NaN,"14,700원",112905012.0,0,N,2017.0
8569,65654,자기계발 코칭전문가 5,"우리는 지금 어떤 시대에 살고 있는가? 포노 사피엔스 시대!(스마트폰 시대)20,0...",자기계발,BOOKK(부크크),최보규,NaN,"25,300원",112904997.0,0,N,2017.0
6391,31192,이상 시 전집,한국문학사에서 유례를 찾기 힘들 만큼 실험적이고 전위적인 문학적 조형 언어로 ‘시각...,소설/시/희곡,민음사,이상,5880.0,"16,000원",112219465.0,0,N,2017.0

In [21]:
df_non_sorted[df_non_sorted['best'] == 'Y']

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
51188,33777,합리적 남자,남자와 여자가 짝짓기 대상을 선택하는 방식이 다른 것은 인간의 DNA에 깊이 새겨져...,자기계발,아니마,롤로 토마시,2754,"13,000원",20053430.0,5,Y,2023.0
9847,58849,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,390.0,"17,000원",66318782.0,1,Y,2023.0
11831,61019,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,900.0,"13,800원",46906835.0,14,Y,2023.0
54459,66850,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546129.0,2,Y,2023.0
54458,66849,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546136.0,2,Y,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6385,31185,없음의 대명사,“없음은 있었음을 끊임없이 두드릴 것이다”‘웃음’과 ‘울음’이 나란히 놓이고‘무표정...,소설/시/희곡,문학과지성사,오은,9021.0,"12,000원",118785759.0,2,Y,2017.0
6305,6903,풀,일본군 ‘위안부’ 피해 할머니의 삶을 그린 장편 만화평화 발자국 열아홉 번째 책은 ...,사회 정치,보리,김금숙,NaN,"26,000원",44332143.0,1,Y,2017.0
6378,31177,풀꽃,‘자세히 보아야/ 예쁘다// 오래 보아야/ 사랑스럽다// 너도 그렇다.’ 스물넉 자...,소설/시/희곡,지혜,나태주,9744.0,"11,000원",99351974.0,2,Y,2017.0
6392,31193,꽃샘바람에 흔들린다면 너는 꽃,섬세한 언어 감각과 서정성 -삶 속에서 심호흡이 필요할 때가슴으로 암송하는 시들시집...,소설/시/희곡,수오서재,류시화,6303.0,"13,500원",108590831.0,5,Y,2017.0
6436,31239,수학자의 아침,"‘그렇지 않았던 것들’을 포착해내는 아침의 감각1993년 등단한 후 지금까지, 세 ...",소설/시/희곡,문학과지성사,김소연,4026.0,"12,000원",11406090.0,2,Y,2017.0

베스트 셀러 생애주기

In [22]:
df_book_details = pd.read_csv('book_details.csv')

In [23]:
df_book_details

,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID
0,나의 영어 사춘기,"대한민국 대표 영어강사 이시원, 영포자들의 닫힌 말문을 열게하다!8주면 누구나 영어...",국어 외국어 사전,시원스쿨닷컴,이시원,72.0,"13,500원",57717060
1,신경 끄기의 기술,아마존·뉴욕타임스 베스트셀러 1위150만 부 돌파! 아마존 53주 연속 베스트셀러2...,자기계발,갤리온,마크 맨슨,19326.0,"17,800원",54233937
2,82년생 김지영,"공포, 피로, 당황, 놀람, 혼란, 좌절의 연속에 대한 한국 여자의 인생 현장 보고...",소설/시/희곡,민음사,조남주,3306.0,"14,000원",32972572
3,언어의 온도,“말과 글에는 나름의 온도가 있다”말과 글에는 나름의 온도가 있다. 따뜻함과 차가움...,에세이,말글터,이기주,30606.0,"13,800원",30387696
4,랩걸 Lab Girl,"2016년 출간과 함께 베스트셀러에 오르며 뜨거운 관심을 받은 <랩걸-나무, 과학 ...",자연과학,알마,호프 자런,10398.0,"20,000원",36390807
...,...,...,...,...,...,...,...,...
77400,2024 해커스군무원 혜원국어 실전동형모의고사 20회분,최신 기출 경향 완벽 반영!20회분의 동형모의고사로 극대화하는 실전 감각!변화하는 ...,수험서 자격증,해커스군무원,고혜원,7962.0,"23,000원",126394099
77401,2024 유휘운 행정법총론 실전동형 모의고사,『2024 유휘운 행정법총론 실전동형 모의고사』는 2024년 공무원 행정법 시험 대...,수험서 자격증,메가스터디교육(공무원),유휘운,24039.0,"9,000원",124838794
77402,ETS 토익 정기시험 실전 1000 Vol. 1 RC(리딩),"토익 실전문제, 이보다 더 완벽할 순 없다!최신 토익시험 경향이 한눈에 보이는 ET...",국어 외국어 사전,YBM(와이비엠),ETS,37827.0,"19,800원",119661061
77403,나혼자 끝내는 독학 일본어 첫걸음,"일본어 20일 기초 완성, 혼자서도 문제 없다!가나&한자 쓰기, 단어 암기, 복습,...",국어 외국어 사전,넥서스JAPANESE,넥서스콘텐츠개발팀,19767.0,"15,000원",116046987
77404,해리포터와 비밀의 방 1,"해리 포터 세대의, 해리 포터 세대를 위한, 해리 포터 세대에 의한 새 번역!‘21...",소설/시/희곡,문학수첩,J.K. 롤링,25395.0,"9,000원",82938415

In [24]:
best_date = pd.read_csv('goods_numbers_with_dates.csv')
best_date

       year  month  data_goods_no
0      2018      1       57717060
1      2018      1       54233937
2      2018      1       32972572
3      2018      1       30387696
4      2018      1       36390807
...     ...    ...            ...
77400  2024      6      126394099
77401  2024      6      124838794
77402  2024      6      119661061
77403  2024      6      116046987
77404  2024      6       82938415

[77405 rows x 3 columns]

In [25]:
best_date.isnull().sum()

year             0
month            0
data_goods_no    0
dtype: int64

In [26]:
date

              출간일         ID    year  month
0      2023-05-10  118755085  2023.0    5.0
1      2024-05-10  126395984  2024.0    5.0
2      2024-06-03  126791092  2024.0    6.0
3      2023-11-06  123317793  2023.0   11.0
4      2019-03-08   69724044  2019.0    3.0
...           ...        ...     ...    ...
297673 2027-07-24  128920663  2027.0    7.0
297674 2024-07-24  128920777  2024.0    7.0
297675 2024-07-23  128928568  2024.0    7.0
297676 2024-07-10  128928919  2024.0    7.0
297677 2024-07-15  128930900  2024.0    7.0

[297678 rows x 4 columns]

In [27]:
date.isnull().sum()

출간일      304
ID         0
year     304
month    304
dtype: int64

In [28]:
# 출간일 2017~2024 자르기
date = date[date['year'] != 2024] 
date = date[date['year'] >= 2017]
date

              출간일         ID    year  month
0      2023-05-10  118755085  2023.0    5.0
3      2023-11-06  123317793  2023.0   11.0
4      2019-03-08   69724044  2019.0    3.0
6      2023-08-30  122091079  2023.0    8.0
9      2023-11-10  123743926  2023.0   11.0
...           ...        ...     ...    ...
297089 2023-09-18  126822330  2023.0    9.0
297250 2023-12-10  127066962  2023.0   12.0
297634 2023-06-12  128818595  2023.0    6.0
297635 2023-06-12  128818647  2023.0    6.0
297673 2027-07-24  128920663  2027.0    7.0

[100084 rows x 4 columns]

In [29]:
date.isnull().sum()

출간일      0
ID       0
year     0
month    0
dtype: int64

In [30]:
# 출간일 2017~2024 자르기
# best_date에서 date의 ID와 data_goods_no가 일치하는 행 필터링 
best_date_filter_2017 = best_date[best_date["data_goods_no"].isin(date["ID"])]

best_date_filter_2017

       year  month  data_goods_no
1      2018      1       54233937
6      2018      1       46659527
7      2018      1       57817824
8      2018      1       57430679
9      2018      1       57430704
...     ...    ...            ...
77365  2024      6       22793441
77379  2024      6       46659527
77390  2024      6      121925411
77391  2024      6      120178685
77404  2024      6       82938415

[16717 rows x 3 columns]

In [31]:
date_filter_2017_b = date[date["ID"].isin(best_date_filter_2017["data_goods_no"])]
date_filter_2017_b

              출간일         ID    year  month
0      2023-05-10  118755085  2023.0    5.0
3      2023-11-06  123317793  2023.0   11.0
4      2019-03-08   69724044  2019.0    3.0
6      2023-08-30  122091079  2023.0    8.0
9      2023-11-10  123743926  2023.0   11.0
...           ...        ...     ...    ...
294887 2023-12-25  124184330  2023.0   12.0
294903 2023-12-22  124201150  2023.0   12.0
294909 2023-12-20  124201716  2023.0   12.0
294948 2023-12-27  124226256  2023.0   12.0
294953 2023-12-21  124227999  2023.0   12.0

[4501 rows x 4 columns]

In [32]:
for idx, row in best_date_filter_2017.iterrows():
    for mer_idx, mer_row in date_filter_2017_b.iterrows():
        if mer_row['ID'] == row['data_goods_no']:
            best_date_filter_2017.at[idx, '출간일'] = mer_row['출간일']

/tmp/ipykernel_222840/2466063951.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  best_date_filter_2017.at[idx, '출간일'] = mer_row['출간일']

In [33]:
best_date_filter_2017

       year  month  data_goods_no        출간일
1      2018      1       54233937 2017-10-27
6      2018      1       46659527 2017-09-22
7      2018      1       57817824 2018-01-08
8      2018      1       57430679 2017-12-12
9      2018      1       57430704 2017-12-12
...     ...    ...            ...        ...
77365  2024      6       22793441 2022-11-14
77379  2024      6       46659527 2017-09-22
77390  2024      6      121925411 2023-08-23
77391  2024      6      120178685 2023-07-27
77404  2024      6       82938415 2019-11-19

[16717 rows x 4 columns]

In [34]:
best_date_filter_2017['year_출간일'] = best_date_filter_2017['출간일'].dt.year

/tmp/ipykernel_222840/246063368.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  best_date_filter_2017['year_출간일'] = best_date_filter_2017['출간일'].dt.year

In [35]:
best_date_filter_2017_restore = best_date_filter_2017

In [36]:
best_date_filter_2017 = best_date_filter_2017[best_date_filter_2017['year'] >= best_date_filter_2017['year_출간일']]

In [37]:
best_date_filter_2017

       year  month  data_goods_no        출간일  year_출간일
1      2018      1       54233937 2017-10-27      2017
6      2018      1       46659527 2017-09-22      2017
7      2018      1       57817824 2018-01-08      2018
8      2018      1       57430679 2017-12-12      2017
9      2018      1       57430704 2017-12-12      2017
...     ...    ...            ...        ...       ...
77365  2024      6       22793441 2022-11-14      2022
77379  2024      6       46659527 2017-09-22      2017
77390  2024      6      121925411 2023-08-23      2023
77391  2024      6      120178685 2023-07-27      2023
77404  2024      6       82938415 2019-11-19      2019

[16336 rows x 5 columns]

In [38]:
df_non_sorted_filtered = df_non_sorted

In [39]:
df_non_sorted_filtered

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
11853,61041,나는 야한 여자가 좋다,"도덕보다는 본능을, 이성보다는 감성을쉽고 재미있게 읽히는 경쾌한 에세이, 21년만의...",에세이,북리뷰,마광수,294.0,"13,000원",3745571.0,0,N,2023.0
51555,63780,뱀파이어의 별 2,"'뱀파이어의 꽃' 그 마지막 입맞춤,영원불멸의 뱀파이어 로맨스!‘말해서는 안 돼. ...",소설/시/희곡,테라스북,신지은,138.0,"14,500원",29373471.0,0,N,2023.0
51292,33906,수거물 폐기물,■ 사랑의 기억을 모으고 나누고 버리고… 마음이 심플해지는 감정정리법!-카피라이터 ...,에세이,폭스코너,신주희,12.0,"13,800원",20181557.0,0,N,2023.0
53713,36582,군인의 품격,"군인엄마의, 희망군대 만들기 프로젝트아들에게도 엄마에게도, 637일간의 인생수업대한...",에세이,더블엔,최혜경,12,"13,000원",30146604.0,0,N,2023.0
54414,66804,무녀굴,<한국 공포 문학 단편선>에 꾸준히 단편을 발표해 오며 실력을 닦아 온 신진오 작가...,소설/시/희곡,황금가지,신진오,126.0,"13,800원",4096725.0,0,N,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8570,65655,자기계발 코칭전문가 4,"우리는 지금 어떤 시대에 살고 있는가? 포노 사피엔스 시대!(스마트폰 시대)20,0...",자기계발,BOOKK(부크크),최보규,NaN,"15,100원",112905001.0,0,N,2017.0
29816,68589,모두가 예술이다,계간 문예지 『시와세계』와 『현대불교신문』이 공동으로 제정한 <이상시문학상>은 시인...,소설/시/희곡,시와세계,이승훈,NaN,"8,000원",3081397.0,0,N,2017.0
8573,65658,자기계발 코칭전문가 1,"우리는 지금 어떤 시대에 살고 있는가? 포노 사피엔스 시대!(스마트폰 시대)20,0...",자기계발,BOOKK(부크크),최보규,NaN,"14,700원",112905012.0,0,N,2017.0
8569,65654,자기계발 코칭전문가 5,"우리는 지금 어떤 시대에 살고 있는가? 포노 사피엔스 시대!(스마트폰 시대)20,0...",자기계발,BOOKK(부크크),최보규,NaN,"25,300원",112904997.0,0,N,2017.0
6391,31192,이상 시 전집,한국문학사에서 유례를 찾기 힘들 만큼 실험적이고 전위적인 문학적 조형 언어로 ‘시각...,소설/시/희곡,민음사,이상,5880.0,"16,000원",112219465.0,0,N,2017.0

In [40]:
df_non_sorted_filtered_best = df_non_sorted_filtered[df_non_sorted_filtered['best'] == 'Y']
df_non_sorted_filtered_best

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
51188,33777,합리적 남자,남자와 여자가 짝짓기 대상을 선택하는 방식이 다른 것은 인간의 DNA에 깊이 새겨져...,자기계발,아니마,롤로 토마시,2754,"13,000원",20053430.0,5,Y,2023.0
9847,58849,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,390.0,"17,000원",66318782.0,1,Y,2023.0
11831,61019,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,900.0,"13,800원",46906835.0,14,Y,2023.0
54459,66850,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546129.0,2,Y,2023.0
54458,66849,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546136.0,2,Y,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6385,31185,없음의 대명사,“없음은 있었음을 끊임없이 두드릴 것이다”‘웃음’과 ‘울음’이 나란히 놓이고‘무표정...,소설/시/희곡,문학과지성사,오은,9021.0,"12,000원",118785759.0,2,Y,2017.0
6305,6903,풀,일본군 ‘위안부’ 피해 할머니의 삶을 그린 장편 만화평화 발자국 열아홉 번째 책은 ...,사회 정치,보리,김금숙,NaN,"26,000원",44332143.0,1,Y,2017.0
6378,31177,풀꽃,‘자세히 보아야/ 예쁘다// 오래 보아야/ 사랑스럽다// 너도 그렇다.’ 스물넉 자...,소설/시/희곡,지혜,나태주,9744.0,"11,000원",99351974.0,2,Y,2017.0
6392,31193,꽃샘바람에 흔들린다면 너는 꽃,섬세한 언어 감각과 서정성 -삶 속에서 심호흡이 필요할 때가슴으로 암송하는 시들시집...,소설/시/희곡,수오서재,류시화,6303.0,"13,500원",108590831.0,5,Y,2017.0
6436,31239,수학자의 아침,"‘그렇지 않았던 것들’을 포착해내는 아침의 감각1993년 등단한 후 지금까지, 세 ...",소설/시/희곡,문학과지성사,김소연,4026.0,"12,000원",11406090.0,2,Y,2017.0

In [41]:
df_non_sorted_filtered_best = df_non_sorted_filtered_best[df_non_sorted_filtered_best["ID"].isin(best_date_filter_2017["data_goods_no"])]
df_non_sorted_filtered_best

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
9847,58849,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,390.0,"17,000원",66318782.0,1,Y,2023.0
11831,61019,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,900.0,"13,800원",46906835.0,14,Y,2023.0
54459,66850,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546129.0,2,Y,2023.0
54458,66849,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546136.0,2,Y,2023.0
9819,58821,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터『오베라는 남자』를 뛰어넘은프레드릭 배크만의...,소설/시/희곡,다산책방,프레드릭 배크만,2346.0,"15,800원",59674622.0,6,Y,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6414,31215,너의 아름다움이 온통 글이 될까봐,"여전히 깊고,보다 새로우며,전에 없이 다양할 것입니다.한국시에 다가올 파란과 만장을...",소설/시/희곡,문학동네,황유원,7248.0,"12,000원",56940287.0,11,Y,2017.0
6385,31185,없음의 대명사,“없음은 있었음을 끊임없이 두드릴 것이다”‘웃음’과 ‘울음’이 나란히 놓이고‘무표정...,소설/시/희곡,문학과지성사,오은,9021.0,"12,000원",118785759.0,2,Y,2017.0
6305,6903,풀,일본군 ‘위안부’ 피해 할머니의 삶을 그린 장편 만화평화 발자국 열아홉 번째 책은 ...,사회 정치,보리,김금숙,NaN,"26,000원",44332143.0,1,Y,2017.0
6378,31177,풀꽃,‘자세히 보아야/ 예쁘다// 오래 보아야/ 사랑스럽다// 너도 그렇다.’ 스물넉 자...,소설/시/희곡,지혜,나태주,9744.0,"11,000원",99351974.0,2,Y,2017.0
6392,31193,꽃샘바람에 흔들린다면 너는 꽃,섬세한 언어 감각과 서정성 -삶 속에서 심호흡이 필요할 때가슴으로 암송하는 시들시집...,소설/시/희곡,수오서재,류시화,6303.0,"13,500원",108590831.0,5,Y,2017.0

In [42]:
df_non_sorted_filtered_nonbest =  df_non_sorted_filtered[df_non_sorted_filtered['best'] == 'N']
df_non_sorted_filtered_nonbest

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
11853,61041,나는 야한 여자가 좋다,"도덕보다는 본능을, 이성보다는 감성을쉽고 재미있게 읽히는 경쾌한 에세이, 21년만의...",에세이,북리뷰,마광수,294.0,"13,000원",3745571.0,0,N,2023.0
51555,63780,뱀파이어의 별 2,"'뱀파이어의 꽃' 그 마지막 입맞춤,영원불멸의 뱀파이어 로맨스!‘말해서는 안 돼. ...",소설/시/희곡,테라스북,신지은,138.0,"14,500원",29373471.0,0,N,2023.0
51292,33906,수거물 폐기물,■ 사랑의 기억을 모으고 나누고 버리고… 마음이 심플해지는 감정정리법!-카피라이터 ...,에세이,폭스코너,신주희,12.0,"13,800원",20181557.0,0,N,2023.0
53713,36582,군인의 품격,"군인엄마의, 희망군대 만들기 프로젝트아들에게도 엄마에게도, 637일간의 인생수업대한...",에세이,더블엔,최혜경,12,"13,000원",30146604.0,0,N,2023.0
54414,66804,무녀굴,<한국 공포 문학 단편선>에 꾸준히 단편을 발표해 오며 실력을 닦아 온 신진오 작가...,소설/시/희곡,황금가지,신진오,126.0,"13,800원",4096725.0,0,N,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
8570,65655,자기계발 코칭전문가 4,"우리는 지금 어떤 시대에 살고 있는가? 포노 사피엔스 시대!(스마트폰 시대)20,0...",자기계발,BOOKK(부크크),최보규,NaN,"15,100원",112905001.0,0,N,2017.0
29816,68589,모두가 예술이다,계간 문예지 『시와세계』와 『현대불교신문』이 공동으로 제정한 <이상시문학상>은 시인...,소설/시/희곡,시와세계,이승훈,NaN,"8,000원",3081397.0,0,N,2017.0
8573,65658,자기계발 코칭전문가 1,"우리는 지금 어떤 시대에 살고 있는가? 포노 사피엔스 시대!(스마트폰 시대)20,0...",자기계발,BOOKK(부크크),최보규,NaN,"14,700원",112905012.0,0,N,2017.0
8569,65654,자기계발 코칭전문가 5,"우리는 지금 어떤 시대에 살고 있는가? 포노 사피엔스 시대!(스마트폰 시대)20,0...",자기계발,BOOKK(부크크),최보규,NaN,"25,300원",112904997.0,0,N,2017.0
6391,31192,이상 시 전집,한국문학사에서 유례를 찾기 힘들 만큼 실험적이고 전위적인 문학적 조형 언어로 ‘시각...,소설/시/희곡,민음사,이상,5880.0,"16,000원",112219465.0,0,N,2017.0

In [43]:
df_non_sorted_filtered_finalmerged = pd.concat([df_non_sorted_filtered_nonbest, df_non_sorted_filtered_best])
df_non_sorted_filtered_finalmerged

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
11853,61041,나는 야한 여자가 좋다,"도덕보다는 본능을, 이성보다는 감성을쉽고 재미있게 읽히는 경쾌한 에세이, 21년만의...",에세이,북리뷰,마광수,294.0,"13,000원",3745571.0,0,N,2023.0
51555,63780,뱀파이어의 별 2,"'뱀파이어의 꽃' 그 마지막 입맞춤,영원불멸의 뱀파이어 로맨스!‘말해서는 안 돼. ...",소설/시/희곡,테라스북,신지은,138.0,"14,500원",29373471.0,0,N,2023.0
51292,33906,수거물 폐기물,■ 사랑의 기억을 모으고 나누고 버리고… 마음이 심플해지는 감정정리법!-카피라이터 ...,에세이,폭스코너,신주희,12.0,"13,800원",20181557.0,0,N,2023.0
53713,36582,군인의 품격,"군인엄마의, 희망군대 만들기 프로젝트아들에게도 엄마에게도, 637일간의 인생수업대한...",에세이,더블엔,최혜경,12,"13,000원",30146604.0,0,N,2023.0
54414,66804,무녀굴,<한국 공포 문학 단편선>에 꾸준히 단편을 발표해 오며 실력을 닦아 온 신진오 작가...,소설/시/희곡,황금가지,신진오,126.0,"13,800원",4096725.0,0,N,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
6414,31215,너의 아름다움이 온통 글이 될까봐,"여전히 깊고,보다 새로우며,전에 없이 다양할 것입니다.한국시에 다가올 파란과 만장을...",소설/시/희곡,문학동네,황유원,7248.0,"12,000원",56940287.0,11,Y,2017.0
6385,31185,없음의 대명사,“없음은 있었음을 끊임없이 두드릴 것이다”‘웃음’과 ‘울음’이 나란히 놓이고‘무표정...,소설/시/희곡,문학과지성사,오은,9021.0,"12,000원",118785759.0,2,Y,2017.0
6305,6903,풀,일본군 ‘위안부’ 피해 할머니의 삶을 그린 장편 만화평화 발자국 열아홉 번째 책은 ...,사회 정치,보리,김금숙,NaN,"26,000원",44332143.0,1,Y,2017.0
6378,31177,풀꽃,‘자세히 보아야/ 예쁘다// 오래 보아야/ 사랑스럽다// 너도 그렇다.’ 스물넉 자...,소설/시/희곡,지혜,나태주,9744.0,"11,000원",99351974.0,2,Y,2017.0
6392,31193,꽃샘바람에 흔들린다면 너는 꽃,섬세한 언어 감각과 서정성 -삶 속에서 심호흡이 필요할 때가슴으로 암송하는 시들시집...,소설/시/희곡,수오서재,류시화,6303.0,"13,500원",108590831.0,5,Y,2017.0

In [44]:
df_non_sorted_filtered_finalmerged['장르'].unique()

array(['에세이', '소설/시/희곡', '자기계발', '사회 정치'], dtype=object)

##### Down Sampling

In [45]:
# 장르별 데이터 개수
genre_counts = df_non_sorted_filtered_nonbest['장르'].value_counts()

# 장르별 비율 계산 (전체 대비 비율)
genre_percentage = genre_counts / len(df_non_sorted_filtered_nonbest) * 100

# 결과 출력
genre_percentage

장르
소설/시/희곡    60.065133
사회 정치      15.317788
에세이        14.438399
자기계발       10.178680
Name: count, dtype: float64

In [46]:
# 베스트 셀러와 비베스트 셀러 데이터 분리
bestsellers = df_non_sorted_filtered_best
non_bestsellers = df_non_sorted_filtered_nonbest

1:3

In [47]:
# 베스트 셀러 장르 비율
genre_distribution = {
    '소설/시/희곡': 60.065133,
    '에세이': 14.438399,
    '자기계발': 10.178680,
    '사회 정치': 15.317788
}

# 목표 총 개수
target_count = 4887

# 각 장르별 샘플 수 계산
samples_per_genre = {genre: int((percentage / 100) * target_count) for genre, percentage in genre_distribution.items()}

# 샘플 수가 해당 장르의 데이터 개수를 초과하지 않도록 조정
downsampled_non_bestsellers = pd.DataFrame()

for genre, num_samples in samples_per_genre.items():
    genre_data = non_bestsellers[non_bestsellers['장르'] == genre]
    if len(genre_data) < num_samples:
        num_samples = len(genre_data)  # 장르 데이터가 부족하면 전체 데이터 개수로 설정
    genre_samples = genre_data.sample(n=num_samples, replace=True)  # 필요시 중복 허용
    downsampled_non_bestsellers = pd.concat([downsampled_non_bestsellers, genre_samples])

# 최종 데이터프레임 생성
final_dataset_3 = pd.concat([bestsellers, downsampled_non_bestsellers])

# 결과 출력 및 확인
print("총 데이터 개수:", len(final_dataset_3))
final_dataset_3

총 데이터 개수: 6514

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
9847,58849,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,390.0,"17,000원",66318782.0,1,Y,2023.0
11831,61019,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,900.0,"13,800원",46906835.0,14,Y,2023.0
54459,66850,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546129.0,2,Y,2023.0
54458,66849,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546136.0,2,Y,2023.0
9819,58821,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터『오베라는 남자』를 뛰어넘은프레드릭 배크만의...,소설/시/희곡,다산책방,프레드릭 배크만,2346.0,"15,800원",59674622.0,6,Y,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
37062,42326,"코로나 시대, 마을교육공동체운동과 생태적 교육학","돌봄 사회, 돌봄 민주주의를 촉구하며 변혁 교육으로의 전환을 준비하다코로나19 팬데...",사회 정치,살림터,심성보,12.0,"17,000원",97701536.0,0,N,2017.0
36078,41187,시대의 경계에서 일인칭으로 말 걸기,"팬데믹, 뉴 노멀, 4차 산업혁명, 부동산, 일자리 문제, 교육 문제……불안과 위험...",사회 정치,해냄에듀,김진경,NaN,"15,000원",107907890.0,0,N,2022.0
12095,13137,지경학의 이론과 실제,이 책은 남북관계와 관련하여 영토의 통일을 목표로 한 지정학적 접근법에서 벗어나 시...,사회 정치,바른북스,임종식,NaN,"15,000원",103304919.0,0,N,2021.0
47236,58587,쉽게 풀어 쓴 노동법,'쉽게 풀어 쓴 노동법'은 CEO와 인사·노무 실무자들이 꼭 알고 있어야 할 노무지...,사회 정치,푸른겨울,박현웅,NaN,"44,000원",110832459.0,0,N,2020.0
28407,32636,협동조합과 괴산지역 공동체운동,괴산지역 민간 주도의부락개발·협동조합·농민운동을 넘어생명살림운동으로의 전환과 공동체...,사회 정치,한살림,김소남,12.0,"20,000원",119862266.0,0,N,2023.0

In [48]:
# 장르별 데이터 개수
genre_counts = final_dataset_3['장르'].value_counts()

# 장르별 비율 계산 (전체 대비 비율)
genre_percentage = genre_counts / len(final_dataset_3) * 100

# 결과 출력
genre_percentage

장르
소설/시/희곡    54.313786
사회 정치      16.456862
에세이        16.287995
자기계발       12.941357
Name: count, dtype: float64

1:4

In [49]:
# 베스트 셀러 장르 비율
genre_distribution = {
    '소설/시/희곡': 60.065133,
    '에세이': 14.438399,
    '자기계발': 10.178680,
    '사회 정치': 15.317788
}

# 목표 총 개수
target_count = 6516

# 각 장르별 샘플 수 계산
samples_per_genre = {genre: int((percentage / 100) * target_count) for genre, percentage in genre_distribution.items()}

# 샘플 수가 해당 장르의 데이터 개수를 초과하지 않도록 조정
downsampled_non_bestsellers = pd.DataFrame()

for genre, num_samples in samples_per_genre.items():
    genre_data = non_bestsellers[non_bestsellers['장르'] == genre]
    if len(genre_data) < num_samples:
        num_samples = len(genre_data)  # 장르 데이터가 부족하면 전체 데이터 개수로 설정
    genre_samples = genre_data.sample(n=num_samples, replace=True)  # 필요시 중복 허용
    downsampled_non_bestsellers = pd.concat([downsampled_non_bestsellers, genre_samples])

# 최종 데이터프레임 생성
final_dataset_4 = pd.concat([bestsellers, downsampled_non_bestsellers])

# 결과 출력 및 확인
print("총 데이터 개수:", len(final_dataset_4))
final_dataset_4

총 데이터 개수: 8143

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
9847,58849,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,390.0,"17,000원",66318782.0,1,Y,2023.0
11831,61019,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,900.0,"13,800원",46906835.0,14,Y,2023.0
54459,66850,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546129.0,2,Y,2023.0
54458,66849,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546136.0,2,Y,2023.0
9819,58821,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터『오베라는 남자』를 뛰어넘은프레드릭 배크만의...,소설/시/희곡,다산책방,프레드릭 배크만,2346.0,"15,800원",59674622.0,6,Y,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
48253,60091,슬기로운 생활과 법률,오늘날 법의 사회적 비중은 더욱 커져가고 있다. 법은 일상생활과 정치 경제사회 문화...,사회 정치,형설출판사,이환경,36.0,"40,000원",117446361.0,0,N,2022.0
40888,46641,한국 언론의 공정성,‘공정성’ 개념은 공정한가?언론이 올바로 서기 위해서는 ‘공정성’ 개념부터 제대로 ...,사회 정치,컬처룩,조항제,12.0,"30,000원",86145480.0,0,N,2019.0
2840,3009,가짜뉴스 전쟁 큰글씨책,가짜뉴스로 인한 정보 혼돈은 세상에 불신과 혐오를 전파시키고 분열과 증오를 일으킨다...,사회 정치,커뮤니케이션북스,하재식,NaN,"27,000원",82418495.0,0,N,2017.0
43411,51246,서울 교통정책 변천사 1953~2016,섬세한 시선으로 시대를 관통하다!교통 분야 전문가가 정리한 서울의 교통정책 변천 보...,사회 정치,서울연구원,이광훈,NaN,"27,000원",57468004.0,0,N,2017.0
22594,25228,사회계약론,사회마다 환경이 다르니 사람들의 삶 역시 다르다.또 환경이 같더라도 사람마다 삶의 ...,사회 정치,살림출판사,오수웅,NaN,"9,800원",101921171.0,0,N,2021.0

In [50]:
# 장르별 데이터 개수
genre_counts = final_dataset_4['장르'].value_counts()

# 장르별 비율 계산 (전체 대비 비율)
genre_percentage = genre_counts / len(final_dataset_4) * 100

# 결과 출력
genre_percentage

장르
소설/시/희곡    55.458676
사회 정치      16.234803
에세이        15.915510
자기계발       12.391011
Name: count, dtype: float64

1:5

In [51]:
# 베스트 셀러 장르 비율
genre_distribution = {
    '소설/시/희곡': 60.065133,
    '에세이': 14.438399,
    '자기계발': 10.178680,
    '사회 정치': 15.317788
}

# 목표 총 개수
target_count = 8145

# 각 장르별 샘플 수 계산
samples_per_genre = {genre: int((percentage / 100) * target_count) for genre, percentage in genre_distribution.items()}

# 샘플 수가 해당 장르의 데이터 개수를 초과하지 않도록 조정
downsampled_non_bestsellers = pd.DataFrame()

for genre, num_samples in samples_per_genre.items():
    genre_data = non_bestsellers[non_bestsellers['장르'] == genre]
    if len(genre_data) < num_samples:
        num_samples = len(genre_data)  # 장르 데이터가 부족하면 전체 데이터 개수로 설정
    genre_samples = genre_data.sample(n=num_samples, replace=True)  # 필요시 중복 허용
    downsampled_non_bestsellers = pd.concat([downsampled_non_bestsellers, genre_samples])

# 최종 데이터프레임 생성
final_dataset_5 = pd.concat([bestsellers, downsampled_non_bestsellers])

# 결과 출력 및 확인
print("총 데이터 개수:", len(final_dataset_5))
final_dataset_5

총 데이터 개수: 9773

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
9847,58849,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,390.0,"17,000원",66318782.0,1,Y,2023.0
11831,61019,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,900.0,"13,800원",46906835.0,14,Y,2023.0
54459,66850,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546129.0,2,Y,2023.0
54458,66849,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,"15,800원",65546136.0,2,Y,2023.0
9819,58821,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터『오베라는 남자』를 뛰어넘은프레드릭 배크만의...,소설/시/희곡,다산책방,프레드릭 배크만,2346.0,"15,800원",59674622.0,6,Y,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
10515,11330,유관순 열사는 투표할 수 없다!,책은 다음과 같이 4부 34장으로 구성되어 있다. 먼저 1부는 국회와 국회의원이다....,사회 정치,BOOKK(부크크),김도경,474.0,"19,000원",88417749.0,0,N,2023.0
19930,22100,트랜스크리틱,"『트랜스크리틱―칸트와 맑스』는 ‘맑스를 칸트로부터 읽고, 칸트를 맑스로부터 읽는’ ...",사회 정치,b(도서출판비),가라타니 고진,204.0,"26,000원",11146758.0,0,N,2023.0
10055,10856,현대 정당의 이해,정당은 현대 민주주의와 시민사회를 정치적으로 제대로 대표하는가?‘민주정치=정당정치’...,사회 정치,한국학술정보,홍득표,36.0,"30,000원",126984693.0,0,N,2021.0
31884,36407,"특수교사, 별이 될 일상수업을 꿈꾸다","교사에게는 일상수업 별자리가 필요하다. 각종 행정업무를 처리하느라 몸이 지치고, 학...",사회 정치,교육과학사,이선희,876.0,"20,000원",115161409.0,0,N,2018.0
1653,1673,대한민국 파괴자 문재인 정권 실체,체제전복·민생추락· 국방붕괴· 국민선동한번도 경험해 보지 못한 문재인 정권 5년의 ...,사회 정치,자유민주아카데미,고영주,96.0,"30,000원",116436937.0,0,N,2022.0

In [52]:
# 장르별 데이터 개수
genre_counts = final_dataset_5['장르'].value_counts()

# 장르별 비율 계산 (전체 대비 비율)
genre_percentage = genre_counts / len(final_dataset_5) * 100

# 결과 출력
genre_percentage

장르
소설/시/희곡    56.226338
사회 정치      16.074900
에세이        15.675842
자기계발       12.022920
Name: count, dtype: float64

#### Pre-Processing

In [53]:
# 판매가 열에서 숫자만 추출하여 정수형으로 변환
final_dataset_5['판매가'] = final_dataset_5['판매가'].str.replace('원', '').str.replace(',', '').astype(float)
final_dataset_5

,index,도서 이름,줄거리,장르,출판사,작가,판매지수,판매가,ID,month,best,year
9847,58849,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,390.0,17000.0,66318782.0,1,Y,2023.0
11831,61019,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,900.0,13800.0,46906835.0,14,Y,2023.0
54459,66850,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,15800.0,65546129.0,2,Y,2023.0
54458,66849,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,108.0,15800.0,65546136.0,2,Y,2023.0
9819,58821,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터『오베라는 남자』를 뛰어넘은프레드릭 배크만의...,소설/시/희곡,다산책방,프레드릭 배크만,2346.0,15800.0,59674622.0,6,Y,2023.0
...,...,...,...,...,...,...,...,...,...,...,...,...
10515,11330,유관순 열사는 투표할 수 없다!,책은 다음과 같이 4부 34장으로 구성되어 있다. 먼저 1부는 국회와 국회의원이다....,사회 정치,BOOKK(부크크),김도경,474.0,19000.0,88417749.0,0,N,2023.0
19930,22100,트랜스크리틱,"『트랜스크리틱―칸트와 맑스』는 ‘맑스를 칸트로부터 읽고, 칸트를 맑스로부터 읽는’ ...",사회 정치,b(도서출판비),가라타니 고진,204.0,26000.0,11146758.0,0,N,2023.0
10055,10856,현대 정당의 이해,정당은 현대 민주주의와 시민사회를 정치적으로 제대로 대표하는가?‘민주정치=정당정치’...,사회 정치,한국학술정보,홍득표,36.0,30000.0,126984693.0,0,N,2021.0
31884,36407,"특수교사, 별이 될 일상수업을 꿈꾸다","교사에게는 일상수업 별자리가 필요하다. 각종 행정업무를 처리하느라 몸이 지치고, 학...",사회 정치,교육과학사,이선희,876.0,20000.0,115161409.0,0,N,2018.0
1653,1673,대한민국 파괴자 문재인 정권 실체,체제전복·민생추락· 국방붕괴· 국민선동한번도 경험해 보지 못한 문재인 정권 5년의 ...,사회 정치,자유민주아카데미,고영주,96.0,30000.0,116436937.0,0,N,2022.0

In [55]:
# 필요한 컬럼 선택
final_dataset_5 = final_dataset_5[["도서 이름", "줄거리", "장르", "출판사", "작가", "판매가", "best"]]

# 결과 출력
final_dataset_5

,도서 이름,줄거리,장르,출판사,작가,판매가,best
9847,받은 만큼 복수하는 소녀,"리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...",소설/시/희곡,문학동네,다비드 라게르크란츠,17000.0,Y
11831,"나, 있는 그대로 참 좋다","지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...",에세이,허밍버드,조유미,13800.0,Y
54459,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,15800.0,Y
54458,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,15800.0,Y
9819,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터『오베라는 남자』를 뛰어넘은프레드릭 배크만의...,소설/시/희곡,다산책방,프레드릭 배크만,15800.0,Y
...,...,...,...,...,...,...,...
10515,유관순 열사는 투표할 수 없다!,책은 다음과 같이 4부 34장으로 구성되어 있다. 먼저 1부는 국회와 국회의원이다....,사회 정치,BOOKK(부크크),김도경,19000.0,N
19930,트랜스크리틱,"『트랜스크리틱―칸트와 맑스』는 ‘맑스를 칸트로부터 읽고, 칸트를 맑스로부터 읽는’ ...",사회 정치,b(도서출판비),가라타니 고진,26000.0,N
10055,현대 정당의 이해,정당은 현대 민주주의와 시민사회를 정치적으로 제대로 대표하는가?‘민주정치=정당정치’...,사회 정치,한국학술정보,홍득표,30000.0,N
31884,"특수교사, 별이 될 일상수업을 꿈꾸다","교사에게는 일상수업 별자리가 필요하다. 각종 행정업무를 처리하느라 몸이 지치고, 학...",사회 정치,교육과학사,이선희,20000.0,N
1653,대한민국 파괴자 문재인 정권 실체,체제전복·민생추락· 국방붕괴· 국민선동한번도 경험해 보지 못한 문재인 정권 5년의 ...,사회 정치,자유민주아카데미,고영주,30000.0,N

In [56]:
final_dataset_5.to_csv('final_dataset_5.csv', index=False)

In [57]:
final_dataset_5_copy = final_dataset_5

- kobert embedding

In [ ]:
from transformers import BertTokenizer, BertModel
import torch

# KoBERT 모델과 토크나이저 불러오기
tokenizer = BertTokenizer.from_pretrained('monologg/kobert')
model = BertModel.from_pretrained('monologg/kobert')

In [ ]:
# '도서 이름' 임베딩
input_texts_name = final_dataset_5['도서 이름'].tolist()
inputs_name = tokenizer(input_texts_name, return_tensors='pt', padding=True, truncation=True)

with torch.no_grad():
    outputs_name = model(**inputs_name)
    
# 도서 이름의 임베딩 결과
name_embeddings = outputs_name.last_hidden_state[:, 0, :].numpy()

# '줄거리' 임베딩
input_texts_desc = final_dataset_5['줄거리'].tolist()
inputs_desc = tokenizer(input_texts_desc, return_tensors='pt', padding=True, truncation=True)

with torch.no_grad():
    outputs_desc = model(**inputs_desc)

# 줄거리의 임베딩 결과
desc_embeddings = outputs_desc.last_hidden_state[:, 0, :].numpy()

# 결과: 두 개의 임베딩을 각각 반환
print("도서 이름 임베딩:", name_embeddings)
print("줄거리 임베딩:", desc_embeddings)

- word2vec embedding

In [60]:
import pandas as pd
import re
from bs4 import BeautifulSoup

# '줄거리' 열 전처리 함수
def preprocess_text(text):
    if pd.isna(text):
        return text
    
    # HTML 태그 제거
    text = BeautifulSoup(text, "html.parser").get_text()

    return text

# '출거리' 열 전처리 적용
final_dataset_5['줄거리'] = final_dataset_5['줄거리'].apply(preprocess_text)
final_dataset_5['작가'] = final_dataset_5['작가'].apply(preprocess_text)


# 결과 출력
final_dataset_5['줄거리'].head()

/tmp/ipykernel_222840/17000953.py:11: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  text = BeautifulSoup(text, "html.parser").get_text()
/tmp/ipykernel_222840/17000953.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataset_5['줄거리'] = final_dataset_5['줄거리'].apply(preprocess_text)
/tmp/ipykernel_222840/17000953.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataset_5['작가'] = final_dataset_5['작가'].apply(preprocess_text)

9847     리스베트, 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리...
11831    지금껏 애써 온 나를 위한 선물“충분히 반짝였던 2018년의 당신,내년에도 당신의 ...
54459    미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...
54458    미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...
9819     눈부신 스토리텔러이자 인간 감정의 마스터『오베라는 남자』를 뛰어넘은프레드릭 배크만의...
Name: 줄거리, dtype: object

In [61]:
import pandas as pd
import re
from nltk.tokenize import sent_tokenize, word_tokenize

# 필요 없는 문자 제거 함수 (괄호 []는 제거하지 않음)
def remove_unwanted_chars(tokens):
    if isinstance(tokens, list):
        return [remove_unwanted_chars(token) for token in tokens]
    elif isinstance(tokens, str):
        return re.sub(r'[^\[\]가-힣a-zA-Z0-9\s]', '', tokens)
    else:
        return tokens

# 필요 없는 문자 제거 적용 (괄호 []는 제거하지 않음)
final_dataset_5['줄거리'] = final_dataset_5['줄거리'].apply(lambda x: remove_unwanted_chars(x))
final_dataset_5['장르'] = final_dataset_5['장르'].apply(lambda x: remove_unwanted_chars(x))

final_dataset_5

/tmp/ipykernel_222840/2702166520.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataset_5['줄거리'] = final_dataset_5['줄거리'].apply(lambda x: remove_unwanted_chars(x))

,도서 이름,줄거리,장르,출판사,작가,판매가,best,도서 이름 토큰화,줄거리 토큰화
9847,받은 만큼 복수하는 소녀,리스베트 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리즈...,소설/시/희곡,문학동네,다비드 라게르크란츠,17000.0,Y,"[받은, 만큼, 복수, 하는, 소녀]","[리스베트, ,, 여자, 교도소, 에, 수감, 되다, 그리고, 마침내, 밝혀지는, ..."
11831,"나, 있는 그대로 참 좋다",지금껏 애써 온 나를 위한 선물충분히 반짝였던 2018년의 당신내년에도 당신의 노력...,에세이,허밍버드,조유미,13800.0,Y,"[나, ,, 있는, 그대로, 참, 좋다]","[지금껏, 애써, 온, 나를, 위, 한, 선물, “, 충분히, 반짝였던, 2018년..."
54459,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,15800.0,Y,"[비탄, 의, 문, 1]","[미스터리, 와, 판타지, 의, 절묘한, 융합, 장르, 의, 벽, 을, 깨는, 미야..."
54458,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,15800.0,Y,"[비탄, 의, 문, 2]","[미스터리, 와, 판타지, 의, 절묘한, 융합, 장르, 의, 벽, 을, 깨는, 미야..."
9819,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터오베라는 남자를 뛰어넘은프레드릭 배크만의 새...,소설/시/희곡,다산책방,프레드릭 배크만,15800.0,Y,"[베어, 타운]","[눈부신, 스토리, 텔러, 이자, 인간, 감정, 의, 마스터, 『, 오, 베, 라는..."
...,...,...,...,...,...,...,...,...,...
10515,유관순 열사는 투표할 수 없다!,책은 다음과 같이 4부 34장으로 구성되어 있다 먼저 1부는 국회와 국회의원이다 국...,사회 정치,BOOKK(부크크),김도경,19000.0,N,"[유관순, 열사, 는, 투표, 할, 수, 없다, !]","[책, 은, 다음, 과, 같이, 4, 부, 34, 장, 으로, 구성, 되어, 있다,..."
19930,트랜스크리틱,트랜스크리틱칸트와 맑스는 맑스를 칸트로부터 읽고 칸트를 맑스로부터 읽는 작업이다 하...,사회 정치,b(도서출판비),가라타니 고진,26000.0,N,"[트랜스, 크리, 틱]","[『, 트랜스, 크리, 틱, ―, 칸트, 와, 맑스, 』, 는, ‘, 맑스, 를, ..."
10055,현대 정당의 이해,정당은 현대 민주주의와 시민사회를 정치적으로 제대로 대표하는가민주정치정당정치라는 등...,사회 정치,한국학술정보,홍득표,30000.0,N,"[현대, 정당, 의, 이해]","[정당, 은, 현대, 민주주의, 와, 시민사회, 를, 정치, 적, 으로, 제대로, ..."
31884,"특수교사, 별이 될 일상수업을 꿈꾸다",교사에게는 일상수업 별자리가 필요하다 각종 행정업무를 처리하느라 몸이 지치고 학생과...,사회 정치,교육과학사,이선희,20000.0,N,"[특수, 교사, ,, 별, 이, 될, 일상, 수업, 을, 꿈꾸다]","[교사, 에게는, 일상, 수업, 별자리, 가, 필요하다, ., 각종, 행정, 업무,..."
1653,대한민국 파괴자 문재인 정권 실체,체제전복민생추락 국방붕괴 국민선동한번도 경험해 보지 못한 문재인 정권 5년의 실체를...,사회 정치,자유민주아카데미,고영주,30000.0,N,"[대한민국, 파괴, 자, 문재인, 정권, 실체]","[체제, 전복, ·, 민생, 추락, ·, 국방, 붕괴, ·, 국민, 선동, 한번, ..."

In [65]:
import pandas as pd
import re
from nltk.tokenize import sent_tokenize, word_tokenize

# 불용어 파일 불러오기
with open('bulyong_a.txt', 'r', encoding='utf-8') as file:
    stop_words = set(file.read().splitlines())

# 불용어 제거 함수
def remove_stop_words(tokens):
    if isinstance(tokens, list):
        return [remove_stop_words(token) for token in tokens if token]
    elif isinstance(tokens, str):
        return ' '.join([word for word in tokens.split() if word not in stop_words])
    else:
        return tokens

In [66]:
# 불용어 제거 적용
final_dataset_5['줄거리 토큰화'] = final_dataset_5['줄거리 토큰화'].apply(remove_stop_words)
final_dataset_5['도서 이름 토큰화'] = final_dataset_5['도서 이름 토큰화'].apply(remove_stop_words)

# 결과 출력
final_dataset_5

/tmp/ipykernel_222840/3333467954.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataset_5['줄거리 토큰화'] = final_dataset_5['줄거리 토큰화'].apply(remove_stop_words)

,도서 이름,줄거리,장르,출판사,작가,판매가,best,도서 이름 토큰화,줄거리 토큰화
9847,받은 만큼 복수하는 소녀,리스베트 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리즈...,소설/시/희곡,문학동네,다비드 라게르크란츠,17000.0,Y,"[받은, 만큼, 복수, 하는, 소녀]","[리스베트, ,, 여자, 교도소, , 수감, 되다, , 마침내, 밝혀지는, 용, 문..."
11831,"나, 있는 그대로 참 좋다",지금껏 애써 온 나를 위한 선물충분히 반짝였던 2018년의 당신내년에도 당신의 노력...,에세이,허밍버드,조유미,13800.0,Y,"[나, ,, 있는, 그대로, 참, 좋다]","[지금껏, 애써, 온, 나를, 위, 한, 선물, “, 충분히, 반짝였던, 2018년..."
54459,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,15800.0,Y,"[비탄, 의, 문, 1]","[미스터리, , 판타지, , 절묘한, 융합, 장르, , 벽, , 깨는, 미야, 베,..."
54458,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,15800.0,Y,"[비탄, 의, 문, 2]","[미스터리, , 판타지, , 절묘한, 융합, 장르, , 벽, , 깨는, 미야, 베,..."
9819,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터오베라는 남자를 뛰어넘은프레드릭 배크만의 새...,소설/시/희곡,다산책방,프레드릭 배크만,15800.0,Y,"[베어, 타운]","[눈부신, 스토리, 텔러, 이자, 인간, 감정, , 마스터, 『, , 베, 라는, ..."
...,...,...,...,...,...,...,...,...,...
10515,유관순 열사는 투표할 수 없다!,책은 다음과 같이 4부 34장으로 구성되어 있다 먼저 1부는 국회와 국회의원이다 국...,사회 정치,BOOKK(부크크),김도경,19000.0,N,"[유관순, 열사, 는, 투표, 할, 수, 없다, !]","[책, 은, , , , 4, 부, 34, 장, , 구성, 되어, , ., 먼저, 1..."
19930,트랜스크리틱,트랜스크리틱칸트와 맑스는 맑스를 칸트로부터 읽고 칸트를 맑스로부터 읽는 작업이다 하...,사회 정치,b(도서출판비),가라타니 고진,26000.0,N,"[트랜스, 크리, 틱]","[『, 트랜스, 크리, 틱, ―, 칸트, , 맑스, 』, 는, ‘, 맑스, , 칸트..."
10055,현대 정당의 이해,정당은 현대 민주주의와 시민사회를 정치적으로 제대로 대표하는가민주정치정당정치라는 등...,사회 정치,한국학술정보,홍득표,30000.0,N,"[현대, 정당, 의, 이해]","[정당, 은, 현대, 민주주의, , 시민사회, , 정치, 적, , 제대로, 대표, ..."
31884,"특수교사, 별이 될 일상수업을 꿈꾸다",교사에게는 일상수업 별자리가 필요하다 각종 행정업무를 처리하느라 몸이 지치고 학생과...,사회 정치,교육과학사,이선희,20000.0,N,"[특수, 교사, ,, 별, 이, 될, 일상, 수업, 을, 꿈꾸다]","[교사, 에게는, 일상, 수업, 별자리, , 필요하다, ., , 행정, 업무, , ..."
1653,대한민국 파괴자 문재인 정권 실체,체제전복민생추락 국방붕괴 국민선동한번도 경험해 보지 못한 문재인 정권 5년의 실체를...,사회 정치,자유민주아카데미,고영주,30000.0,N,"[대한민국, 파괴, 자, 문재인, 정권, 실체]","[체제, 전복, ·, 민생, 추락, ·, 국방, 붕괴, ·, 국민, 선동, 한번, ..."

In [67]:
# 특수 문자 제거 함수
def remove_special_chars(token_list):
    if isinstance(token_list, list):
        return [re.sub(r'[^\w\s]', '', token) for token in token_list]
    return token_list

# '형태소 토큰화_줄거리' 열에 함수 적용
final_dataset_5['줄거리 토큰화'] = final_dataset_5['줄거리 토큰화'].apply(remove_special_chars)
c

/tmp/ipykernel_222840/3593272829.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataset_5['줄거리 토큰화'] = final_dataset_5['줄거리 토큰화'].apply(remove_special_chars)

,도서 이름,줄거리,장르,출판사,작가,판매가,best,도서 이름 토큰화,줄거리 토큰화
9847,받은 만큼 복수하는 소녀,리스베트 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리즈...,소설/시/희곡,문학동네,다비드 라게르크란츠,17000.0,Y,"[받은, 만큼, 복수, 하는, 소녀]","[리스베트, , 여자, 교도소, , 수감, 되다, , 마침내, 밝혀지는, 용, 문신..."
11831,"나, 있는 그대로 참 좋다",지금껏 애써 온 나를 위한 선물충분히 반짝였던 2018년의 당신내년에도 당신의 노력...,에세이,허밍버드,조유미,13800.0,Y,"[나, ,, 있는, 그대로, 참, 좋다]","[지금껏, 애써, 온, 나를, 위, 한, 선물, , 충분히, 반짝였던, 2018년,..."
54459,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,15800.0,Y,"[비탄, 의, 문, 1]","[미스터리, , 판타지, , 절묘한, 융합, 장르, , 벽, , 깨는, 미야, 베,..."
54458,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,15800.0,Y,"[비탄, 의, 문, 2]","[미스터리, , 판타지, , 절묘한, 융합, 장르, , 벽, , 깨는, 미야, 베,..."
9819,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터오베라는 남자를 뛰어넘은프레드릭 배크만의 새...,소설/시/희곡,다산책방,프레드릭 배크만,15800.0,Y,"[베어, 타운]","[눈부신, 스토리, 텔러, 이자, 인간, 감정, , 마스터, , , 베, 라는, 남..."
...,...,...,...,...,...,...,...,...,...
10515,유관순 열사는 투표할 수 없다!,책은 다음과 같이 4부 34장으로 구성되어 있다 먼저 1부는 국회와 국회의원이다 국...,사회 정치,BOOKK(부크크),김도경,19000.0,N,"[유관순, 열사, 는, 투표, 할, 수, 없다, !]","[책, 은, , , , 4, 부, 34, 장, , 구성, 되어, , , 먼저, 1,..."
19930,트랜스크리틱,트랜스크리틱칸트와 맑스는 맑스를 칸트로부터 읽고 칸트를 맑스로부터 읽는 작업이다 하...,사회 정치,b(도서출판비),가라타니 고진,26000.0,N,"[트랜스, 크리, 틱]","[, 트랜스, 크리, 틱, , 칸트, , 맑스, , 는, , 맑스, , 칸트, , ..."
10055,현대 정당의 이해,정당은 현대 민주주의와 시민사회를 정치적으로 제대로 대표하는가민주정치정당정치라는 등...,사회 정치,한국학술정보,홍득표,30000.0,N,"[현대, 정당, 의, 이해]","[정당, 은, 현대, 민주주의, , 시민사회, , 정치, 적, , 제대로, 대표, ..."
31884,"특수교사, 별이 될 일상수업을 꿈꾸다",교사에게는 일상수업 별자리가 필요하다 각종 행정업무를 처리하느라 몸이 지치고 학생과...,사회 정치,교육과학사,이선희,20000.0,N,"[특수, 교사, ,, 별, 이, 될, 일상, 수업, 을, 꿈꾸다]","[교사, 에게는, 일상, 수업, 별자리, , 필요하다, , , 행정, 업무, , 처..."
1653,대한민국 파괴자 문재인 정권 실체,체제전복민생추락 국방붕괴 국민선동한번도 경험해 보지 못한 문재인 정권 5년의 실체를...,사회 정치,자유민주아카데미,고영주,30000.0,N,"[대한민국, 파괴, 자, 문재인, 정권, 실체]","[체제, 전복, , 민생, 추락, , 국방, 붕괴, , 국민, 선동, 한번, 도, ..."

In [68]:
# 연속된 콤마를 하나로 바꾸고, 콤마 뒤에 대괄호가 바로 오는 경우 대괄호로만 대체하고 콤마 뒤에 텍스트가 없는 경우 콤마 삭제
def replace_multiple_commas(text):
    if isinstance(text, list):
        return [replace_multiple_commas(subtext) for subtext in text if subtext]  # 값이 없는 요소 삭제
    if isinstance(text, str):
        text = re.sub(r',\s*,+', ',', text)
        text = re.sub(r',\s*\]', ']', text)
        text = re.sub(r',\s*$', '', text)  # 콤마 뒤에 텍스트가 없으면 콤마 삭제
    return text

final_dataset_5['줄거리 토큰화'] = final_dataset_5['줄거리 토큰화'].apply(replace_multiple_commas)
final_dataset_5['도서 이름 토큰화'] = final_dataset_5['도서 이름 토큰화'].apply(replace_multiple_commas)
final_dataset_5

/tmp/ipykernel_222840/1979050603.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataset_5['줄거리 토큰화'] = final_dataset_5['줄거리 토큰화'].apply(replace_multiple_commas)

,도서 이름,줄거리,장르,출판사,작가,판매가,best,도서 이름 토큰화,줄거리 토큰화
9847,받은 만큼 복수하는 소녀,리스베트 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리즈...,소설/시/희곡,문학동네,다비드 라게르크란츠,17000.0,Y,"[받은, 만큼, 복수, 하는, 소녀]","[리스베트, 여자, 교도소, 수감, 되다, 마침내, 밝혀지는, 용, 문신, 비밀, ..."
11831,"나, 있는 그대로 참 좋다",지금껏 애써 온 나를 위한 선물충분히 반짝였던 2018년의 당신내년에도 당신의 노력...,에세이,허밍버드,조유미,13800.0,Y,"[나, ,, 있는, 그대로, 참, 좋다]","[지금껏, 애써, 온, 나를, 위, 한, 선물, 충분히, 반짝였던, 2018년, 내..."
54459,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,15800.0,Y,"[비탄, 의, 문, 1]","[미스터리, 판타지, 절묘한, 융합, 장르, 벽, 깨는, 미야, 베, 월드, 수많은..."
54458,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,15800.0,Y,"[비탄, 의, 문, 2]","[미스터리, 판타지, 절묘한, 융합, 장르, 벽, 깨는, 미야, 베, 월드, 수많은..."
9819,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터오베라는 남자를 뛰어넘은프레드릭 배크만의 새...,소설/시/희곡,다산책방,프레드릭 배크만,15800.0,Y,"[베어, 타운]","[눈부신, 스토리, 텔러, 이자, 인간, 감정, 마스터, 베, 라는, 남자, 뛰어넘..."
...,...,...,...,...,...,...,...,...,...
10515,유관순 열사는 투표할 수 없다!,책은 다음과 같이 4부 34장으로 구성되어 있다 먼저 1부는 국회와 국회의원이다 국...,사회 정치,BOOKK(부크크),김도경,19000.0,N,"[유관순, 열사, 는, 투표, 할, 수, 없다, !]","[책, 은, 4, 부, 34, 장, 구성, 되어, 먼저, 1, 부는, 국회, 국회의..."
19930,트랜스크리틱,트랜스크리틱칸트와 맑스는 맑스를 칸트로부터 읽고 칸트를 맑스로부터 읽는 작업이다 하...,사회 정치,b(도서출판비),가라타니 고진,26000.0,N,"[트랜스, 크리, 틱]","[트랜스, 크리, 틱, 칸트, 맑스, 는, 맑스, 칸트, 읽고, 칸트, 맑스, 읽는..."
10055,현대 정당의 이해,정당은 현대 민주주의와 시민사회를 정치적으로 제대로 대표하는가민주정치정당정치라는 등...,사회 정치,한국학술정보,홍득표,30000.0,N,"[현대, 정당, 의, 이해]","[정당, 은, 현대, 민주주의, 시민사회, 정치, 적, 제대로, 대표, 하는가, 민..."
31884,"특수교사, 별이 될 일상수업을 꿈꾸다",교사에게는 일상수업 별자리가 필요하다 각종 행정업무를 처리하느라 몸이 지치고 학생과...,사회 정치,교육과학사,이선희,20000.0,N,"[특수, 교사, ,, 별, 이, 될, 일상, 수업, 을, 꿈꾸다]","[교사, 에게는, 일상, 수업, 별자리, 필요하다, 행정, 업무, 처리, 하느라, ..."
1653,대한민국 파괴자 문재인 정권 실체,체제전복민생추락 국방붕괴 국민선동한번도 경험해 보지 못한 문재인 정권 5년의 실체를...,사회 정치,자유민주아카데미,고영주,30000.0,N,"[대한민국, 파괴, 자, 문재인, 정권, 실체]","[체제, 전복, 민생, 추락, 국방, 붕괴, 국민, 선동, 한번, 도, 경험, 해,..."

In [74]:
final_dataset_5

,도서 이름,줄거리,장르,출판사,작가,판매가,best,도서 이름 토큰화,줄거리 토큰화
9847,받은 만큼 복수하는 소녀,리스베트 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리즈...,소설/시/희곡,문학동네,다비드 라게르크란츠,17000.0,Y,"[받은, 복수, 하는, 소녀]","[리스베트, 여자, 교도소, 수감, 되다, 마침내, 밝혀지는, 용, 문신, 비밀, ..."
11831,"나, 있는 그대로 참 좋다",지금껏 애써 온 나를 위한 선물충분히 반짝였던 2018년의 당신내년에도 당신의 노력...,에세이,허밍버드,조유미,13800.0,Y,"[있는, 그대로, 좋다]","[지금껏, 애써, 온, 나를, 위, 한, 선물, 충분히, 반짝였던, 2018년, 내..."
54459,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,15800.0,Y,"[비탄, 문, 1]","[미스터리, 판타지, 절묘한, 융합, 장르, 벽, 깨는, 미야, 베, 월드, 수많은..."
54458,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,15800.0,Y,"[비탄, 문, 2]","[미스터리, 판타지, 절묘한, 융합, 장르, 벽, 깨는, 미야, 베, 월드, 수많은..."
9819,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터오베라는 남자를 뛰어넘은프레드릭 배크만의 새...,소설/시/희곡,다산책방,프레드릭 배크만,15800.0,Y,"[베어, 타운]","[눈부신, 스토리, 텔러, 이자, 인간, 감정, 마스터, 베, 라는, 남자, 뛰어넘..."
...,...,...,...,...,...,...,...,...,...
10515,유관순 열사는 투표할 수 없다!,책은 다음과 같이 4부 34장으로 구성되어 있다 먼저 1부는 국회와 국회의원이다 국...,사회 정치,BOOKK(부크크),김도경,19000.0,N,"[유관순, 열사, 는, 투표, 할, 수, 없다]","[책, 은, 4, 부, 34, 장, 구성, 되어, 먼저, 1, 부는, 국회, 국회의..."
19930,트랜스크리틱,트랜스크리틱칸트와 맑스는 맑스를 칸트로부터 읽고 칸트를 맑스로부터 읽는 작업이다 하...,사회 정치,b(도서출판비),가라타니 고진,26000.0,N,"[트랜스, 크리, 틱]","[트랜스, 크리, 틱, 칸트, 맑스, 는, 맑스, 칸트, 읽고, 칸트, 맑스, 읽는..."
10055,현대 정당의 이해,정당은 현대 민주주의와 시민사회를 정치적으로 제대로 대표하는가민주정치정당정치라는 등...,사회 정치,한국학술정보,홍득표,30000.0,N,"[현대, 정당, 이해]","[정당, 은, 현대, 민주주의, 시민사회, 정치, 적, 제대로, 대표, 하는가, 민..."
31884,"특수교사, 별이 될 일상수업을 꿈꾸다",교사에게는 일상수업 별자리가 필요하다 각종 행정업무를 처리하느라 몸이 지치고 학생과...,사회 정치,교육과학사,이선희,20000.0,N,"[특수, 교사, 별, 될, 일상, 수업, 꿈꾸다]","[교사, 에게는, 일상, 수업, 별자리, 필요하다, 행정, 업무, 처리, 하느라, ..."
1653,대한민국 파괴자 문재인 정권 실체,체제전복민생추락 국방붕괴 국민선동한번도 경험해 보지 못한 문재인 정권 5년의 실체를...,사회 정치,자유민주아카데미,고영주,30000.0,N,"[대한민국, 파괴, 문재인, 정권, 실체]","[체제, 전복, 민생, 추락, 국방, 붕괴, 국민, 선동, 한번, 도, 경험, 해,..."

In [79]:
from gensim.models import Word2Vec
import numpy as np

# '줄거리 토큰화' 열에서 문장 목록 가져오기
sentences = final_dataset_5['줄거리 토큰화'].tolist()

# Word2Vec 임베딩
word2vec_model = Word2Vec(sentences, vector_size=100, window=5, min_count=1, workers=4)

# 각 줄거리에 대한 Word2Vec 임베딩 계산
final_dataset_5['Word2Vec_임베딩'] = final_dataset_5['줄거리 토큰화'].apply(
    lambda x: np.mean([word2vec_model.wv[word] for word in x if word in word2vec_model.wv.key_to_index], axis=0)
)

# 결과 출력
final_dataset_5

/tmp/ipykernel_222840/2002855691.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataset_5['Word2Vec_임베딩'] = final_dataset_5['줄거리 토큰화'].apply(

,도서 이름,줄거리,장르,출판사,작가,판매가,best,도서 이름 토큰화,줄거리 토큰화,Word2Vec_임베딩
9847,받은 만큼 복수하는 소녀,리스베트 여자 교도소에 수감되다그리고 마침내 밝혀지는 용 문신의 비밀밀레니엄 시리즈...,소설/시/희곡,문학동네,다비드 라게르크란츠,17000.0,Y,"[받은, 복수, 하는, 소녀]","[리스베트, 여자, 교도소, 수감, 되다, 마침내, 밝혀지는, 용, 문신, 비밀, ...","[-0.09319226, 0.6226734, 0.06540484, 0.1986603..."
11831,"나, 있는 그대로 참 좋다",지금껏 애써 온 나를 위한 선물충분히 반짝였던 2018년의 당신내년에도 당신의 노력...,에세이,허밍버드,조유미,13800.0,Y,"[있는, 그대로, 좋다]","[지금껏, 애써, 온, 나를, 위, 한, 선물, 충분히, 반짝였던, 2018년, 내...","[0.017434347, 0.36726278, 0.28314382, 0.231880..."
54459,비탄의 문 1,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,15800.0,Y,"[비탄, 문, 1]","[미스터리, 판타지, 절묘한, 융합, 장르, 벽, 깨는, 미야, 베, 월드, 수많은...","[-0.1023553, 0.66065204, 0.22699684, 0.3654538..."
54458,비탄의 문 2,미스터리와 판타지의 절묘한 융합장르의 벽을 깨는 미야베 월드수많은 말이 살아 움직이...,소설/시/희곡,문학동네,미야베 미유키,15800.0,Y,"[비탄, 문, 2]","[미스터리, 판타지, 절묘한, 융합, 장르, 벽, 깨는, 미야, 베, 월드, 수많은...","[-0.1023553, 0.66065204, 0.22699684, 0.3654538..."
9819,베어타운,눈부신 스토리텔러이자 인간 감정의 마스터오베라는 남자를 뛰어넘은프레드릭 배크만의 새...,소설/시/희곡,다산책방,프레드릭 배크만,15800.0,Y,"[베어, 타운]","[눈부신, 스토리, 텔러, 이자, 인간, 감정, 마스터, 베, 라는, 남자, 뛰어넘...","[0.08493435, 0.70082283, 0.23855594, 0.3192264..."
...,...,...,...,...,...,...,...,...,...,...
10515,유관순 열사는 투표할 수 없다!,책은 다음과 같이 4부 34장으로 구성되어 있다 먼저 1부는 국회와 국회의원이다 국...,사회 정치,BOOKK(부크크),김도경,19000.0,N,"[유관순, 열사, 는, 투표, 할, 수, 없다]","[책, 은, 4, 부, 34, 장, 구성, 되어, 먼저, 1, 부는, 국회, 국회의...","[-0.3981716, 0.35674122, 0.24921925, 0.2089306..."
19930,트랜스크리틱,트랜스크리틱칸트와 맑스는 맑스를 칸트로부터 읽고 칸트를 맑스로부터 읽는 작업이다 하...,사회 정치,b(도서출판비),가라타니 고진,26000.0,N,"[트랜스, 크리, 틱]","[트랜스, 크리, 틱, 칸트, 맑스, 는, 맑스, 칸트, 읽고, 칸트, 맑스, 읽는...","[-0.29587725, 0.51557523, 0.342027, 0.26945224..."
10055,현대 정당의 이해,정당은 현대 민주주의와 시민사회를 정치적으로 제대로 대표하는가민주정치정당정치라는 등...,사회 정치,한국학술정보,홍득표,30000.0,N,"[현대, 정당, 이해]","[정당, 은, 현대, 민주주의, 시민사회, 정치, 적, 제대로, 대표, 하는가, 민...","[-0.33897346, 0.3839301, 0.2155117, 0.23903573..."
31884,"특수교사, 별이 될 일상수업을 꿈꾸다",교사에게는 일상수업 별자리가 필요하다 각종 행정업무를 처리하느라 몸이 지치고 학생과...,사회 정치,교육과학사,이선희,20000.0,N,"[특수, 교사, 별, 될, 일상, 수업, 꿈꾸다]","[교사, 에게는, 일상, 수업, 별자리, 필요하다, 행정, 업무, 처리, 하느라, ...","[-0.17165576, 0.26330212, 0.60400856, 0.543958..."
1653,대한민국 파괴자 문재인 정권 실체,체제전복민생추락 국방붕괴 국민선동한번도 경험해 보지 못한 문재인 정권 5년의 실체를...,사회 정치,자유민주아카데미,고영주,30000.0,N,"[대한민국, 파괴, 문재인, 정권, 실체]","[체제, 전복, 민생, 추락, 국방, 붕괴, 국민, 선동, 한번, 도, 경험, 해,...","[-0.26418167, 0.40720513, -0.05402247, 0.16016..."

In [80]:
# 각 줄거리에 대한 Word2Vec 임베딩 계산
final_dataset_5['도서_이름_Word2Vec_임베딩'] = final_dataset_5['도서 이름 토큰화'].apply(
    lambda x: np.mean([word2vec_model.wv[word] for word in x if word in word2vec_model.wv.key_to_index], axis=0)
)

/home/alsghk01/다운로드/줄거리를 통한 도서 평점 예측2/myenv/lib64/python3.9/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alsghk01/다운로드/줄거리를 통한 도서 평점 예측2/myenv/lib64/python3.9/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/tmp/ipykernel_222840/953089059.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataset_5['도서_이름_Word2Vec_임베딩'] = final_dataset_5['도서 이름 토큰화'].apply(

In [83]:
# 각 줄거리에 대한 Word2Vec 임베딩 계산
final_dataset_5['장르_Word2Vec_임베딩'] = final_dataset_5['장르'].apply(
    lambda x: np.mean([word2vec_model.wv[word] for word in x if word in word2vec_model.wv.key_to_index], axis=0)
)
final_dataset_5['출판사_Word2Vec_임베딩'] = final_dataset_5['출판사'].apply(
    lambda x: np.mean([word2vec_model.wv[word] for word in x if word in word2vec_model.wv.key_to_index], axis=0)
)
final_dataset_5['작가_Word2Vec_임베딩'] = final_dataset_5['작가'].apply(
    lambda x: np.mean([word2vec_model.wv[word] for word in x if word in word2vec_model.wv.key_to_index], axis=0)
)

/home/alsghk01/다운로드/줄거리를 통한 도서 평점 예측2/myenv/lib64/python3.9/site-packages/numpy/core/fromnumeric.py:3432: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/alsghk01/다운로드/줄거리를 통한 도서 평점 예측2/myenv/lib64/python3.9/site-packages/numpy/core/_methods.py:190: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)

TypeError: 'float' object is not iterable

- fasttext embedding

##### Train-Test Split

##### Modeling